osrs_items = ["20th anniversary boots",
    "20th anniversary bottom",
    "20th anniversary cape",
    "20th anniversary gloves",
    "20th anniversary hat",
    "20th anniversary necklace",
    "20th anniversary top",
    "'24-carat' sword",
    "4th birthday hat",
    "9mm revolver",
    "A big present",
    "A eyeglo null",
    "A stone bowl (RuneScape 2 Beta)",
    "Abyssal whip (Last Man Standing)",
    "Abyssal whip (My Arm's Big Adventure)",
    "Ad coupon",
    "Adamant 2h sword",
    "Adamant arrow",
    "Adamant arrow pack",
    "Adamant axe",
    "Adamant axe head",
    "Adamant battleaxe",
    "Adamant chainbody",
    "Adamant dagger",
    "Adamant full helm",
    "Adamant full helm (g)",
    "Adamant full helm (t)",
    "Adamant gloves (Last Man Standing)",
    "Adamant gold-trimmed set (lg)",
    "Adamant gold-trimmed set (sk)",
    "Adamant helm (h1)",
    "Adamant helm (h2)",
    "Adamant helm (h3)",
    "Adamant helm (h4)",
    "Adamant helm (h5)",
    "Adamant kiteshield",
    "Adamant kiteshield (g)",
    "Adamant kiteshield (t)",
    "Adamant longsword",
    "Adamant mace",
    "Adamant med helm",
    "Adamant pick head",
    "Adamant pickaxe",
    "Adamant platebody",
    "Adamant platebody (g)",
    "Adamant platebody (h1)",
    "Adamant platebody (h2)",
    "Adamant platebody (h3)",
    "Adamant platebody (h4)",
    "Adamant platebody (h5)",
    "Adamant platebody (t)",
    "Adamant platelegs",
    "Adamant platelegs (g)",
    "Adamant platelegs (t)",
    "Adamant plateskirt",
    "Adamant plateskirt (g)",
    "Adamant plateskirt (t)",
    "Adamant scimitar",
    "Adamant set (lg)",
    "Adamant set (sk)",
    "Adamant shield (h1)",
    "Adamant shield (h2)",
    "Adamant shield (h3)",
    "Adamant shield (h4)",
    "Adamant shield (h5)",
    "Adamant sq shield",
    "Adamant sword",
    "Adamant trimmed set (lg)",
    "Adamant trimmed set (sk)",
    "Adamant warhammer",
    "Adamantite bar",
    "Adamantite ore",
    "Aereck's caged monkey",
    "Ahab's beer",
    "Ahrim's robeskirt (Last Man Standing)",
    "Ahrim's robetop (Last Man Standing)",
    "Ahrim's staff (Last Man Standing)",
    "Air rune",
    "Air rune (Barbarian Assault)",
    "Air rune pack",
    "Air talisman",
    "Air tiara",
    "Al kharid flyer",
    "Amulet mould",
    "Amulet of accuracy",
    "Amulet of defence",
    "Amulet of defence (t)",
    "Amulet of duplication",
    "Amulet of fury (Last Man Standing)",
    "Amulet of glory (Last Man Standing)",
    "Amulet of magic",
    "Amulet of magic (t)",
    "Amulet of power",
    "Amulet of power (Last Man Standing)",
    "Amulet of power (t)",
    "Amulet of strength",
    "Amur leopard toy",
    "Ancestral hat (Last Man Standing)",
    "Anchovies",
    "Anchovy pizza",
    "Ancient astroscope",
    "Ancient carcanet",
    "Ancient casket",
    "Ancient full helm",
    "Ancient globe",
    "Ancient kiteshield",
    "Ancient ledger",
    "Ancient platebody",
    "Ancient platelegs",
    "Ancient plateskirt",
    "Ancient rune armour set (lg)",
    "Ancient rune armour set (sk)",
    "Ancient treatise",
    "Anim offhand",
    "Anti-dragon shield",
    "Anti-panties",
    "Anti-present",
    "Antipoison",
    "Antique lamp (X Marks the Spot)",
    "Antisanta boots",
    "Antisanta gloves",
    "Antisanta jacket",
    "Antisanta mask",
    "Antisanta pantaloons",
    "Antisanta's coal box",
    "Apple pie",
    "Armadyl crossbow (Last Man Standing)",
    "Armadyl full helm",
    "Armadyl godsword (Last Man Standing)",
    "Armadyl godsword (RuneFest 2018)",
    "Armadyl kiteshield",
    "Armadyl platebody",
    "Armadyl platelegs",
    "Armadyl plateskirt",
    "Armadyl rune armour set (lg)",
    "Armadyl rune armour set (sk)",
    "Asgarnian ale",
    "Ashes",
    "Astral rune (Barbarian Assault)",
    "Baguette",
    "Bait pack",
    "Bakery storage key",
    "Ball of wool",
    "Bamboo",
    "Banana",
    "Banana (cookout)",
    "Banana hat",
    "Banana pizza (cookout)",
    "Bandages",
    "Bandos full helm",
    "Bandos godsword (Misthalin Mystery)",
    "Bandos kiteshield",
    "Bandos platebody",
    "Bandos platelegs",
    "Bandos plateskirt",
    "Bandos rune armour set (lg)",
    "Bandos rune armour set (sk)",
    "Bandos tassets (Last Man Standing)",
    "Bank filler",
    "Bank note",
    "Banshee mask",
    "Banshee robe",
    "Banshee top",
    "Barricade",
    "Barronite deposit",
    "Barronite guard",
    "Barronite handle",
    "Barronite head",
    "Barronite mace",
    "Barronite shards",
    "Barrows gloves (Last Man Standing)",
    "Battered teddy",
    "Bauble box",
    "Beach boxing gloves",
    "Bear feet",
    "Bear fur",
    "Beautiful yellow pansy seed",
    "Beef fillet",
    "Beekeeper's boots",
    "Beekeeper's gloves",
    "Beekeeper's hat",
    "Beekeeper's legs",
    "Beekeeper's top",
    "Beer",
    "Beer glass",
    "Beer glass of water",
    "Bell bauble",
    "Berserker ring (Last Man Standing)",
    "Big bones",
    "Big bucket",
    "Big bucket of camel milk",
    "Big bucket of frozen camel milk",
    "Big snowball",
    "Birthday balloons",
    "Birthday cake",
    "Birthday cake (Mobile Anniversary)",
    "Birthday present",
    "Bitter chocolate mix",
    "Bitter easter egg",
    "Black 2h sword",
    "Black axe",
    "Black axe head",
    "Black battleaxe",
    "Black bead",
    "Black cape",
    "Black chainbody",
    "Black d'hide body (Last Man Standing)",
    "Black dagger",
    "Black destabiliser",
    "Black full helm",
    "Black full helm (g)",
    "Black full helm (t)",
    "Black goblin mail",
    "Black gold-trimmed set (lg)",
    "Black gold-trimmed set (sk)",
    "Black h'ween mask",
    "Black helm (h1)",
    "Black helm (h2)",
    "Black helm (h3)",
    "Black helm (h4)",
    "Black helm (h5)",
    "Black kiteshield",
    "Black kiteshield (g)",
    "Black kiteshield (t)",
    "Black longsword",
    "Black mace",
    "Black med helm",
    "Black partyhat",
    "Black pick head",
    "Black pickaxe",
    "Black platebody",
    "Black platebody (g)",
    "Black platebody (h1)",
    "Black platebody (h2)",
    "Black platebody (h3)",
    "Black platebody (h4)",
    "Black platebody (h5)",
    "Black platebody (t)",
    "Black platelegs",
    "Black platelegs (g)",
    "Black platelegs (t)",
    "Black plateskirt",
    "Black plateskirt (g)",
    "Black plateskirt (t)",
    "Black robe",
    "Black santa hat",
    "Black scimitar",
    "Black set (lg)",
    "Black set (sk)",
    "Black shield (h1)",
    "Black shield (h2)",
    "Black shield (h3)",
    "Black shield (h4)",
    "Black shield (h5)",
    "Black skirt",
    "Black skirt (g)",
    "Black skirt (t)",
    "Black sq shield",
    "Black sword",
    "Black toy horsey",
    "Black trimmed set (lg)",
    "Black trimmed set (sk)",
    "Black warhammer",
    "Black wizard hat (g)",
    "Black wizard hat (t)",
    "Black wizard robe (g)",
    "Black wizard robe (t)",
    "Blank paper hat",
    "Blessed spirit shield (Last Man Standing)",
    "Blood rune (Barbarian Assault)",
    "Bloodier key",
    "Bloody key",
    "Blue bouncy ball",
    "Blue cape",
    "Blue destabiliser",
    "Blue dye",
    "Blue gingerbread shield",
    "Blue goblin mail",
    "Blue halloween mask",
    "Blue marionette",
    "Blue marionette (arms)",
    "Blue marionette (head)",
    "Blue marionette (legs)",
    "Blue marionette (strung)",
    "Blue marionette (torso)",
    "Blue paper hat",
    "Blue partyhat",
    "Blue partyhat (Draynor Bank Robbery)",
    "Blue rainbow strand",
    "Blue skirt",
    "Blue skirt (g)",
    "Blue skirt (t)",
    "Blue wizard hat",
    "Blue wizard hat (g)",
    "Blue wizard hat (t)",
    "Blue wizard robe",
    "Blue wizard robe (g)",
    "Blue wizard robe (t)",
    "Blunt scimitars",
    "Blurite ore",
    "Blurite sword",
    "Bob (unobtainable item)",
    "Bob's caged monkey",
    "Bobble hat",
    "Bobble scarf",
    "Body core",
    "Body rune",
    "Body rune (Barbarian Assault)",
    "Body talisman",
    "Body tiara",
    "Bone fragments",
    "Bones",
    "Bones (Tutorial Island)",
    "Book (Shield of Arrav)",
    "Book of folklore",
    "Book of knowledge",
    "Book on chickens",
    "Bottom of sceptre",
    "Bowl",
    "Bowl of food (RuneScape 2 Beta)",
    "Bowl of water",
    "Box bauble",
    "Box of chocolate strawberries",
    "Box of delights (unobtainable item)",
    "Bp obj",
    "Brass key",
    "Brass monkey",
    "Brass necklace",
    "Bread",
    "Bread (cookout)",
    "Bread dough",
    "Bread dough (cookout)",
    "Brewer's folly",
    "Broken axe (adamant)",
    "Broken axe (black)",
    "Broken axe (bronze)",
    "Broken axe (dragon)",
    "Broken axe (iron)",
    "Broken axe (mithril)",
    "Broken axe (rune)",
    "Broken axe (steel)",
    "Broken cauldron",
    "Broken egg",
    "Broken goat horn",
    "Broken pickaxe (adamant)",
    "Broken pickaxe (black)",
    "Broken pickaxe (bronze)",
    "Broken pickaxe (dragon)",
    "Broken pickaxe (iron)",
    "Broken pickaxe (mithril)",
    "Broken pickaxe (rune)",
    "Broken pickaxe (steel)",
    "Broken plate",
    "Broken shield",
    "Bronze 2h sword",
    "Bronze arrow",
    "Bronze arrow (Barbarian Assault)",
    "Bronze axe",
    "Bronze axe head",
    "Bronze bar",
    "Bronze battleaxe",
    "Bronze bolts",
    "Bronze chainbody",
    "Bronze dagger",
    "Bronze full helm",
    "Bronze full helm (g)",
    "Bronze full helm (t)",
    "Bronze gold-trimmed set (lg)",
    "Bronze gold-trimmed set (sk)",
    "Bronze key (Prince Ali Rescue)",
    "Bronze kiteshield",
    "Bronze kiteshield (g)",
    "Bronze kiteshield (t)",
    "Bronze longsword",
    "Bronze mace",
    "Bronze med helm",
    "Bronze pick head",
    "Bronze pickaxe",
    "Bronze platebody",
    "Bronze platebody (g)",
    "Bronze platebody (t)",
    "Bronze platelegs",
    "Bronze platelegs (g)",
    "Bronze platelegs (t)",
    "Bronze plateskirt",
    "Bronze plateskirt (g)",
    "Bronze plateskirt (t)",
    "Bronze scimitar",
    "Bronze set (lg)",
    "Bronze set (sk)",
    "Bronze sq shield",
    "Bronze sword",
    "Bronze trimmed set (lg)",
    "Bronze trimmed set (sk)",
    "Bronze warhammer",
    "Brown apron",
    "Brown toy horsey",
    "Bryophyta's essence",
    "Bryophyta's staff",
    "Bucket",
    "Bucket (cookout)",
    "Bucket of milk",
    "Bucket of water",
    "Bucket of water (cookout)",
    "Bucket of wester sand",
    "Bulging sack",
    "Bunny ears",
    "Bunny feet",
    "Bunny legs",
    "Bunny paws",
    "Bunny top",
    "Bunnyman mask",
    "Burnt banana pizza (cookout)",
    "Burnt bones",
    "Burnt bread",
    "Burnt bread (cookout)",
    "Burnt cake",
    "Burnt chicken",
    "Burnt fish (anchovies)",
    "Burnt fish (herring)",
    "Burnt fish (sardine)",
    "Burnt fish (trout)",
    "Burnt fish (tuna)",
    "Burnt lobster",
    "Burnt meat",
    "Burnt pie",
    "Burnt pizza",
    "Burnt pizza (cookout)",
    "Burnt shrimp",
    "Burnt stew",
    "Burnt swordfish",
    "Cabbage",
    "Cabbage (Draynor Manor)",
    "Cabbage (unobtainable item)",
    "Cabbage cape",
    "Cabbage rune",
    "Cadava berries",
    "Cadava potion",
    "Cake",
    "Cake (2020 Easter event)",
    "Cake tin",
    "Camo bottoms",
    "Camo bottoms (unobtainable item)",
    "Camo helmet",
    "Camo helmet (unobtainable item)",
    "Camo top",
    "Camo top (unobtainable item)",
    "Candy cane",
    "Capt' arnav's chest",
    "Carrot",
    "Carrot sword",
    "Carved gem",
    "Casket (Pirate's Treasure)",
    "Castle wars bracelet",
    "Castle wars ticket",
    "Castlewars brew",
    "Castlewars cloak (Saradomin)",
    "Castlewars cloak (Zamorak)",
    "Castlewars hood (Saradomin)",
    "Castlewars hood (Zamorak)",
    "Castlewars manual",
    "Cat ears",
    "Catalytic rune pack",
    "Cauldron of cabbages",
    "Cauldron of water",
    "Cauldron of water & cabbages",
    "Cavefish",
    "Certificate (Shield of Arrav)",
    "Chair",
    "Chaos elemental (unobtainable item)",
    "Chaos rune",
    "Chaos rune (Barbarian Assault)",
    "Chaos rune pack",
    "Chaotic handegg",
    "Charcoal",
    "Cheese",
    "Cheese (cookout)",
    "Chef's hat",
    "Chest key (Pirate's Treasure)",
    "Chicken feet",
    "Chicken head",
    "Chicken legs",
    "Chicken wings",
    "Chisel",
    "Chisel (animation item)",
    "Choco serum",
    "Chocolate bar",
    "Chocolate cake",
    "Chocolate chips",
    "Chocolate chunks",
    "Chocolate chunks (2013 Easter event)",
    "Chocolate dust",
    "Chocolate egg",
    "Chocolate egg (2005 Easter event)",
    "Chocolate kebbit",
    "Chocolate mixture(u)",
    "Chocolate strawberry",
    "Christmas cracker",
    "Chronicle",
    "Church decoration",
    "Church lectern",
    "Churning machine",
    "Clan cloak",
    "Clan vexillum",
    "Clay",
    "Clean full helm",
    "Clean platebody",
    "Clean platelegs",
    "Climbing boots (Last Man Standing)",
    "Climbing rope",
    "Cloak of ruin",
    "Clown bow tie",
    "Clown gown",
    "Clown mask",
    "Clown shoes",
    "Clown trousers",
    "Clue bottle (beginner)",
    "Clue geode (beginner)",
    "Clue nest (beginner)",
    "Clue scroll (beginner)",
    "Clue scroll (special)",
    "Coal",
    "Coconut bunch",
    "Coffin",
    "Coffin nails",
    "Coif",
    "Coins",
    "Coins (My Arm's Big Adventure)",
    "Collection log",
    "Combat achievements (unobtainable item)",
    "Combat path starter kit",
    "Combat path voucher",
    "Community pumpkin",
    "Compost bin (unobtainable item)",
    "Conch shell",
    "Cook's letter",
    "Cook's shopping list",
    "Cooked chicken",
    "Cooked karambwan (Last Man Standing)",
    "Cooked meat",
    "Cooking apple",
    "Cooking pot",
    "Cooler",
    "Copper ore",
    "Cornflour",
    "Cosmic rune",
    "Cosmic rune (Barbarian Assault)",
    "Cow blood",
    "Cow gloves",
    "Cow mask",
    "Cow shoes",
    "Cow tail",
    "Cow top",
    "Cow trousers",
    "Cow's caged monkey",
    "Cowhide",
    "Crab meat (unobtainable item)",
    "Crandor map",
    "Crasher (RuneScape 2 Beta)",
    "Crate of baskets",
    "Crate ring",
    "Crossbow",
    "Cruciferous codex",
    "Crunchy chocolate mix",
    "Crunchy easter egg",
    "Crypt key (2018 Halloween event)",
    "Cube part",
    "Cursed banana",
    "Cursed goblin bow",
    "Cursed goblin hammer",
    "Cursed goblin staff",
    "Damp coal dust",
    "Dark bow (Last Man Standing)",
    "Dead orb",
    "Dead person",
    "Deadman's cape",
    "Deadman's chest",
    "Deadman's legs",
    "Deadwood log",
    "Deadwood plank",
    "Death note",
    "Death rune",
    "Death rune (Barbarian Assault)",
    "Death's coffer (unobtainable item)",
    "Decorative armour (gold platebody)",
    "Decorative armour (gold platelegs)",
    "Decorative armour (gold plateskirt)",
    "Decorative armour (red platebody)",
    "Decorative armour (red platelegs)",
    "Decorative armour (red plateskirt)",
    "Decorative armour (white platebody)",
    "Decorative armour (white platelegs)",
    "Decorative armour (white plateskirt)",
    "Decorative boots (gold)",
    "Decorative boots (red)",
    "Decorative boots (white)",
    "Decorative full helm (gold)",
    "Decorative full helm (red)",
    "Decorative full helm (white)",
    "Decorative helm (gold)",
    "Decorative helm (red)",
    "Decorative helm (white)",
    "Decorative shield (gold)",
    "Decorative shield (red)",
    "Decorative shield (white)",
    "Decorative sword (gold)",
    "Decorative sword (red)",
    "Decorative sword (white)",
    "Deflated blue bouncy ball",
    "Deflated green bouncy ball",
    "Deflated red bouncy ball",
    "Demon feet",
    "Desert bait",
    "Dharok's greataxe (Last Man Standing)",
    "Dharok's helm (Last Man Standing)",
    "Dharok's platebody (Last Man Standing)",
    "Dharok's platelegs (Last Man Standing)",
    "Diamond",
    "Diamond amulet",
    "Diamond amulet (u)",
    "Diamond bauble",
    "Diamond bolts (e) (Last Man Standing)",
    "Diamond necklace",
    "Diamond ring",
    "Diango's claws",
    "Disk of returning",
    "Diving apparatus (2017 Halloween event)",
    "Diving helmet",
    "Donie's caged monkey",
    "Dossier",
    "Dossier (animation item)",
    "Double helix",
    "Dragon arrow (Last Man Standing)",
    "Dragon axe head",
    "Dragon chainbody (My Arm's Big Adventure)",
    "Dragon claws (Last Man Standing)",
    "Dragon dagger (Last Man Standing)",
    "Dragon defender (Last Man Standing)",
    "Dragon javelin (Last Man Standing)",
    "Dragon med helm (My Arm's Big Adventure)",
    "Dragon platelegs (My Arm's Big Adventure)",
    "Dragonstone full helm",
    "Dragonstone platebody",
    "Dragonstone platelegs",
    "Dried cocoa",
    "Druidic wreath",
    "Dummy portal",
    "Dwarf (The Giant Dwarf)",
    "Dwarven stout",
    "Earth rune",
    "Earth rune (Barbarian Assault)",
    "Earth rune pack",
    "Earth talisman",
    "Earth tiara",
    "Earthy chocolate mix",
    "Earthy easter egg",
    "Easter (unobtainable item)",
    "Easter basket",
    "Easter blaster",
    "Easter egg",
    "Easter egg (2022 Easter event)",
    "Easter egg helm",
    "Easter hat",
    "Easter ring",
    "Eek",
    "Egg",
    "Egg mould",
    "Egg mould (2018 Easter event)",
    "Eggshell platebody",
    "Eggshell platelegs",
    "Elaborate lockbox",
    "Elder maul (Last Man Standing)",
    "Elem longsword (RuneScape 2 Beta)",
    "Elemental metal (RuneScape 2 Beta)",
    "Elemental ore (RuneScape 2 Beta)",
    "Elemental rune pack",
    "Elvarg's head",
    "Elven legwear",
    "Elven sheep",
    "Elven skirt (white)",
    "Elven skirt (yellow)",
    "Elven top (white vest)",
    "Elven top (white)",
    "Elven top (yellow vest)",
    "Elven top (yellow)",
    "Emerald",
    "Emerald amulet",
    "Emerald amulet (u)",
    "Emerald key",
    "Emerald necklace",
    "Emerald ring",
    "Empty blaster",
    "Empty bucket pack",
    "Empty jug pack",
    "Empty sack (Christmas 2017)",
    "Empty vial pack",
    "Enchanted curtains",
    "Enchanted snowy curtains",
    "Energy potion",
    "Enjifern",
    "Eternal boots (Last Man Standing)",
    "Evil root",
    "Exploding vial (animation item)",
    "Explosive potion",
    "Eye of newt",
    "Eye of newt pack",
    "Fancy boots",
    "Farmer's fork",
    "Farmer's strawhat (animation item)",
    "Feather",
    "Feather pack",
    "Festive cinnamon",
    "Festive cinnamon stick",
    "Festive egg",
    "Festive elf hat",
    "Festive elf slippers",
    "Festive flour",
    "Festive ginger powder",
    "Festive gingerbread gnomes",
    "Festive holly",
    "Festive mulled wine",
    "Festive pot",
    "Festive tree branch",
    "Festive white wine",
    "Fiendish ashes",
    "Fighting boots",
    "Fine mesh net",
    "Fine red silk",
    "Fine silk",
    "Fire rune",
    "Fire rune (Barbarian Assault)",
    "Fire rune pack",
    "Fire talisman",
    "Fire tiara",
    "Firestarter",
    "Fish food",
    "Fishing bait",
    "Fishing rod",
    "Fishlike thing",
    "Fishmonger (unobtainable item)",
    "Fishy chocolate mix",
    "Fishy easter egg",
    "Flour (unobtainable item)",
    "Flower crown",
    "Fluffy chocolate mix",
    "Fluffy easter egg",
    "Fluffy feathers",
    "Fly fishing rod",
    "Flyer",
    "Footprint (unobtainable item)",
    "Free to play starter pack",
    "Fresh chocolate mix",
    "Fresh easter egg",
    "Frog mask",
    "Frog slippers",
    "Frog token",
    "Frozen churning machine",
    "Fruity chocolate mix",
    "Fruity easter egg",
    "Fur",
    "Garlic",
    "Gertrude's comb",
    "Ghost buster 500",
    "Ghost's skull",
    "Ghostspeak amulet",
    "Ghrazi rapier (Last Man Standing)",
    "Giant boulder",
    "Giant easter egg",
    "Giant key",
    "Giant present",
    "Giants foundry tester",
    "Gilded 2h sword",
    "Gilded armour set (lg)",
    "Gilded armour set (sk)",
    "Gilded axe",
    "Gilded chainbody",
    "Gilded d'hide body",
    "Gilded d'hide chaps",
    "Gilded d'hide vambraces",
    "Gilded dragonhide set",
    "Gilded full helm",
    "Gilded kiteshield",
    "Gilded med helm",
    "Gilded pickaxe",
    "Gilded platebody",
    "Gilded platelegs",
    "Gilded plateskirt",
    "Gilded scimitar",
    "Gilded spade",
    "Gilded sq shield",
    "Gingerbread gnome",
    "Gingerbread shield",
    "Gloves of ruin",
    "Gnome child (item)",
    "Gnome child hat",
    "Gnome child icon",
    "Gnome child mask",
    "Goblin decorations",
    "Goblin gifts",
    "Goblin mail",
    "Goblin paint cannon",
    "Goblin stew",
    "Gold amulet",
    "Gold amulet (u)",
    "Gold bar",
    "Gold dust",
    "Gold fragment",
    "Gold necklace",
    "Gold ore",
    "Gold paint",
    "Gold ring",
    "Golden apron",
    "Golden chef's hat",
    "Golden rings",
    "Gorgeous orange lily seed",
    "Goutweed (My Arm's Big Adventure)",
    "Grain",
    "Granite maul (Last Man Standing)",
    "Grapes",
    "Grass seed",
    "Gravedigger boots",
    "Gravedigger gloves",
    "Gravedigger leggings",
    "Gravedigger mask",
    "Gravedigger top",
    "Gravestone (unobtainable item)",
    "Green banner",
    "Green bouncy ball",
    "Green cape",
    "Green d'hide body",
    "Green d'hide body (g)",
    "Green d'hide body (t)",
    "Green d'hide chaps",
    "Green d'hide chaps (g)",
    "Green d'hide chaps (t)",
    "Green d'hide vambraces",
    "Green destabiliser",
    "Green dragonhide set",
    "Green dye",
    "Green fireflies (item)",
    "Green gingerbread shield",
    "Green goblin mail",
    "Green halloween mask",
    "Green marionette",
    "Green marionette (arms)",
    "Green marionette (head)",
    "Green marionette (legs)",
    "Green marionette (strung)",
    "Green marionette (torso)",
    "Green paper hat",
    "Green partyhat",
    "Green rainbow strand",
    "Gregg's eastdoor",
    "Gregg's iou",
    "Grey gloves",
    "Grey toy horsey",
    "Grim reaper hood",
    "Grim reaper's diary",
    "Grim robe",
    "Grinder (animation item)",
    "Group iron bracers",
    "Group iron bracers (unranked)",
    "Group iron helm",
    "Group iron helm (unranked)",
    "Group iron platebody",
    "Group iron platebody (unranked)",
    "Group iron platelegs",
    "Group iron platelegs (unranked)",
    "Growth potion",
    "Guam in a box?",
    "Gublinch shards",
    "Guppy",
    "Guthan's helm (Last Man Standing)",
    "Guthix armour set (lg)",
    "Guthix armour set (sk)",
    "Guthix full helm",
    "Guthix kiteshield",
    "Guthix platebody",
    "Guthix platelegs",
    "Guthix plateskirt",
    "Halberd (unobtainable item)",
    "Half certificate",
    "Half full wine jug",
    "Halloween mask set",
    "Ham joint",
    "Hammer",
    "Hand fan",
    "Hard leather",
    "Hardcore group iron bracers",
    "Hardcore group iron helm",
    "Hardcore group iron platebody",
    "Hardcore group iron platelegs",
    "Hardcore ironman helm",
    "Hardcore ironman platebody",
    "Hardcore ironman platelegs",
    "Hardleather body",
    "Harpoon",
    "Haunted wine bottle",
    "Headless head",
    "Heavy ballista (Last Man Standing)",
    "Helix fossil",
    "Hell cat ears",
    "Helm of neitiznot (Last Man Standing)",
    "Helpful device (RuneScape 2 Beta)",
    "Herb bowl (animation item)",
    "Herring",
    "Hetty's empty cauldron",
    "Hex edit detected",
    "Hill giant club",
    "Holiday tool",
    "Hollow reed (unobtainable item)",
    "Holy handegg",
    "Holy mould",
    "Holy symbol",
    "Honey",
    "Hood of ruin",
    "Hoop snake (item)",
    "Hornwood helm",
    "Hosidius milk",
    "Hourglass (2014 Halloween event)",
    "Huge snowball",
    "Human bones",
    "Human eye",
    "Humongous snowball",
    "Hunting knife",
    "Ice cream easter egg",
    "Iced gingerbread shield",
    "Idol of balance",
    "Idol of chaos",
    "Idol of light",
    "Imbued guthix cape (Last Man Standing)",
    "Imbued saradomin cape (Last Man Standing)",
    "Imbued zamorak cape (Last Man Standing)",
    "Incantation (2020 Halloween event)",
    "Incomplete blaster",
    "Incomplete pizza",
    "Incomplete pizza (cookout)",
    "Incomplete stew",
    "Infernal cape (Last Man Standing)",
    "Infinite money bag",
    "Intel report",
    "Inverted santa hat",
    "Invitation list",
    "Iodine",
    "Iron 2h sword",
    "Iron arrow",
    "Iron arrow (Barbarian Assault)",
    "Iron axe",
    "Iron axe head",
    "Iron bar",
    "Iron battleaxe",
    "Iron chainbody",
    "Iron dagger",
    "Iron full helm",
    "Iron full helm (g)",
    "Iron full helm (t)",
    "Iron gold-trimmed set (lg)",
    "Iron gold-trimmed set (sk)",
    "Iron kiteshield",
    "Iron kiteshield (g)",
    "Iron kiteshield (t)",
    "Iron longsword",
    "Iron mace",
    "Iron med helm",
    "Iron ore",
    "Iron pick head",
    "Iron pickaxe",
    "Iron platebody",
    "Iron platebody (g)",
    "Iron platebody (t)",
    "Iron platelegs",
    "Iron platelegs (g)",
    "Iron platelegs (t)",
    "Iron plateskirt",
    "Iron plateskirt (g)",
    "Iron plateskirt (t)",
    "Iron scimitar",
    "Iron set (lg)",
    "Iron set (sk)",
    "Iron sq shield",
    "Iron sword",
    "Iron trimmed set (lg)",
    "Iron trimmed set (sk)",
    "Iron warhammer",
    "Ironman helm",
    "Ironman platebody",
    "Ironman platelegs",
    "Jack lantern mask",
    "Jam",
    "Jar of ethereal fluid",
    "Javelin (unobtainable item)",
    "Jered's empty wine bottle",
    "Jester cape",
    "Jester hat",
    "Jester scarf",
    "Jonas mask",
    "Jug",
    "Jug of bad wine",
    "Jug of bad wine (unobtainable item)",
    "Jug of water",
    "Jug of wine",
    "Karamjan rum",
    "Karamjan rum (banana)",
    "Karamjan rum (sliced banana)",
    "Kebab",
    "Key (Ernest the Chicken)",
    "Key (Melzar's Maze)",
    "Key print",
    "Killer's knife",
    "Kindling (2018 Easter event)",
    "King's message",
    "Knife",
    "Knight summoner",
    "Kodai wand (Last Man Standing)",
    "Kree'arra (unobtainable item)",
    "Kristmas kebab",
    "Lamp",
    "Lamp of the gatherer",
    "Large snowball",
    "Law rune",
    "Law rune (Barbarian Assault)",
    "League tomato",
    "Leather",
    "Leather body",
    "Leather body (g)",
    "Leather boots",
    "Leather chaps",
    "Leather chaps (g)",
    "Leather cowl",
    "Leather gloves",
    "Leather vambraces",
    "Lederhosen hat",
    "Lederhosen shorts",
    "Lederhosen top",
    "Left skull half",
    "Left-handed banana",
    "Legendary red rose seed",
    "Lifeboat",
    "Limpwurt root",
    "Lion toy",
    "List of monkey sightings",
    "Lit candle (unobtainable item)",
    "Little snowball",
    "Lobster",
    "Lobster pot",
    "Logs",
    "Logs (Tutorial Island)",
    "Logs and kindling",
    "Longbow",
    "Loose cat hair",
    "Loot key",
    "Lumbridge task list",
    "Mage's book (Last Man Standing)",
    "Magic egg",
    "Magic egg ball",
    "Magic staff",
    "Magical cleaning potion",
    "Magical cleaning potion (2022 Easter event)",
    "Makeover voucher",
    "Manor key",
    "Map part",
    "Maple logs",
    "Maple longbow",
    "Maple shortbow",
    "Maple syrup",
    "Marionette handle",
    "Mask of balance",
    "Maze key",
    "Meat pie",
    "Meat pizza",
    "Meaty chocolate mix",
    "Meaty easter egg",
    "Melted easter egg",
    "Message (Romeo & Juliet)",
    "Mime boots",
    "Mime gloves",
    "Mime legs",
    "Mime mask",
    "Mime top",
    "Mind core",
    "Mind rune",
    "Mind rune (Barbarian Assault)",
    "Mind rune pack",
    "Mind talisman",
    "Mind tiara",
    "Mithril 2h sword",
    "Mithril arrow",
    "Mithril arrow (Barbarian Assault)",
    "Mithril axe",
    "Mithril axe head",
    "Mithril bar",
    "Mithril battleaxe",
    "Mithril chainbody",
    "Mithril dagger",
    "Mithril full helm",
    "Mithril full helm (g)",
    "Mithril full helm (t)",
    "Mithril gold-trimmed set (lg)",
    "Mithril gold-trimmed set (sk)",
    "Mithril kiteshield",
    "Mithril kiteshield (g)",
    "Mithril kiteshield (t)",
    "Mithril longsword",
    "Mithril mace",
    "Mithril med helm",
    "Mithril ore",
    "Mithril pick head",
    "Mithril pickaxe",
    "Mithril platebody",
    "Mithril platebody (g)",
    "Mithril platebody (t)",
    "Mithril platelegs",
    "Mithril platelegs (g)",
    "Mithril platelegs (t)",
    "Mithril plateskirt",
    "Mithril plateskirt (g)",
    "Mithril plateskirt (t)",
    "Mithril scimitar",
    "Mithril set (lg)",
    "Mithril set (sk)",
    "Mithril sq shield",
    "Mithril sword",
    "Mithril trimmed set (lg)",
    "Mithril trimmed set (sk)",
    "Mithril warhammer",
    "Mobile phone",
    "Mole slippers",
    "Monk's robe",
    "Monk's robe (g)",
    "Monk's robe (t)",
    "Monk's robe top",
    "Monk's robe top (g)",
    "Monk's robe top (t)",
    "Monkey bones",
    "Monkey cage",
    "Mop",
    "Morrigan's javelin (Last Man Standing)",
    "Mossy key",
    "Mouldy sawdust",
    "Muddy key",
    "Murky potion",
    "Museum map",
    "Mysterious orb (X Marks the Spot)",
    "Mystery box",
    "Mystic robe bottom (Last Man Standing)",
    "Mystic robe top (Last Man Standing)",
    "Nature rune",
    "Nature rune (Barbarian Assault)",
    "Necklace mould",
    "Needle",
    "New crystal bow (unobtainable item)",
    "New crystal shield (unobtainable item)",
    "Newcomer map",
    "Newspaper",
    "Newspaper (unobtainable item)",
    "Nezikchened's mum",
    "Normal snowball",
    "Note (2017 Halloween event)",
    "Notes (2021 Christmas event)",
    "Notes (2022 Birthday event)",
    "Notes (Misthalin Mystery - 1)",
    "Notes (Misthalin Mystery - 2)",
    "Notes (Misthalin Mystery - 3)",
    "Nuggets (2018 Easter event)",
    "Oak logs",
    "Oak longbow",
    "Oak shortbow",
    "Occult necklace (Last Man Standing)",
    "Oculus orb",
    "Oddskull",
    "Ogre artefact (The Corsair Curse)",
    "Oil can",
    "Old school bond",
    "Olive stuffer",
    "Onion",
    "Orange cape",
    "Orange dye",
    "Orange goblin mail",
    "Orange rainbow strand",
    "Orbital knife",
    "Ornate boots",
    "Ornate cape",
    "Ornate gloves",
    "Ornate helm",
    "Ornate legs",
    "Ornate lockbox",
    "Ornate top",
    "Osman's report",
    "Package",
    "Painted fake magic egg",
    "Partyhat set",
    "Paste",
    "Pastel flowers",
    "Pastry dough",
    "Peaceful handegg",
    "Pear tree sapling",
    "Pearl barbarian rod",
    "Pearl fishing rod",
    "Pearl fly fishing rod",
    "Phoenix crossbow",
    "Phoenix crossbow (unobtainable item)",
    "Phoenix hq key",
    "Pickaxe handle",
    "Pie dish",
    "Pie shell",
    "Pike",
    "Pine tree seed",
    "Pink goblin mail",
    "Pink skirt",
    "Pink stained full helm",
    "Pink stained platebody",
    "Pink stained platelegs",
    "Pirate message",
    "Pizza base",
    "Pizza base (cookout)",
    "Plain pizza",
    "Plain pizza (cookout)",
    "Plank",
    "Platinum token",
    "Poison (item)",
    "Poisoned fish food",
    "Pole (unobtainable item)",
    "Polished blue gem",
    "Portrait",
    "Pot",
    "Pot (cookout)",
    "Pot of flour",
    "Pot of flour (Tutorial Island)",
    "Pot of flour (cookout)",
    "Potato",
    "Potion",
    "Premium banana",
    "Present (2016 Birthday event)",
    "Present (Christmas 2015)",
    "Pressure gauge",
    "Pretty girl",
    "Priest gown (bottom)",
    "Priest gown (top)",
    "Prince leggings",
    "Prince tunic",
    "Princess blouse",
    "Princess skirt",
    "Prison key (Prison Pete)",
    "Promissory note (Christmas 2017)",
    "Prop sword",
    "Prop sword (incomplete)",
    "Propeller hat",
    "Pumpkin",
    "Pumpkin lantern",
    "Pumpkin pie",
    "Puppet box",
    "Pure essence",
    "Purple cape",
    "Purple dye",
    "Purple gloves",
    "Purple goblin mail",
    "Purple partyhat",
    "Purple rainbow strand",
    "Pushup (unobtainable item)",
    "Pyromancer set",
    "Quality violet tulip seed",
    "Rabbit mould",
    "Rainbow partyhat",
    "Rainbow scarf",
    "Ranger path starter kit",
    "Ranging potion (Last Man Standing)",
    "Rat's tail",
    "Raw anchovies",
    "Raw bear meat",
    "Raw beef",
    "Raw boar meat",
    "Raw cavefish",
    "Raw chicken",
    "Raw fishlike thing",
    "Raw guppy",
    "Raw herring",
    "Raw lobster",
    "Raw pheasant",
    "Raw pheasant (historical)",
    "Raw pike",
    "Raw rat meat",
    "Raw salmon",
    "Raw sardine",
    "Raw shrimps",
    "Raw shrimps (Tutorial Island)",
    "Raw swordfish",
    "Raw tetra",
    "Raw trout",
    "Raw tuna",
    "Red bead",
    "Red bouncy ball",
    "Red cape",
    "Red destabiliser",
    "Red dye",
    "Red fireflies (item)",
    "Red gingerbread shield",
    "Red gloves",
    "Red goblin mail",
    "Red halloween mask",
    "Red marionette",
    "Red marionette (arms)",
    "Red marionette (head)",
    "Red marionette (legs)",
    "Red marionette (strung)",
    "Red marionette (torso)",
    "Red paper hat",
    "Red partyhat",
    "Red rainbow strand",
    "Red spiders' eggs",
    "Redberries",
    "Redberry pie",
    "Redundant hat",
    "Redundant leggings",
    "Redundant top",
    "Reindeer hat",
    "Research notes (Rune Mysteries)",
    "Research package",
    "Restored shield (unobtainable item)",
    "Reward casket (beginner)",
    "Rich chocolate mix",
    "Rich easter egg",
    "Rick's box",
    "Rick's head",
    "Right skull half",
    "Ring mould",
    "Ring of 3rd age",
    "Ring of coins",
    "Ring of forging",
    "Ring of nature",
    "Robe bottom of ruin",
    "Robe top of ruin",
    "Rock (2017 Easter event)",
    "Rock (Castle Wars)",
    "Rod with net",
    "Roll",
    "Rope",
    "Rope (Last Man Standing)",
    "Rotten cabbage",
    "Rotten carrot",
    "Rotten egg",
    "Rotten meat",
    "Rotten net",
    "Rotten onion",
    "Rotten potato",
    "Rotten strawberry",
    "Rubber chicken",
    "Rubber chicken (RuneFest 2018)",
    "Rubber tube",
    "Ruby",
    "Ruby amulet",
    "Ruby amulet (u)",
    "Ruby key",
    "Ruby necklace",
    "Ruby ring",
    "Ruined cavefish",
    "Ruined guppy",
    "Ruined tetra",
    "Run (unobtainable item)",
    "Rune 2h sword",
    "Rune armour set (lg)",
    "Rune armour set (sk)",
    "Rune arrow pack",
    "Rune axe",
    "Rune axe head",
    "Rune battleaxe",
    "Rune chainbody",
    "Rune crossbow (Last Man Standing)",
    "Rune dagger",
    "Rune essence",
    "Rune full helm",
    "Rune full helm (g)",
    "Rune full helm (t)",
    "Rune gold-trimmed set (lg)",
    "Rune gold-trimmed set (sk)",
    "Rune helm (h1)",
    "Rune helm (h2)",
    "Rune helm (h3)",
    "Rune helm (h4)",
    "Rune helm (h5)",
    "Rune kiteshield",
    "Rune kiteshield (g)",
    "Rune kiteshield (t)",
    "Rune longsword",
    "Rune mace",
    "Rune med helm",
    "Rune pick head",
    "Rune pickaxe",
    "Rune platebody",
    "Rune platebody (g)",
    "Rune platebody (h1)",
    "Rune platebody (h2)",
    "Rune platebody (h3)",
    "Rune platebody (h4)",
    "Rune platebody (h5)",
    "Rune platebody (t)",
    "Rune platelegs",
    "Rune platelegs (Last Man Standing)",
    "Rune platelegs (g)",
    "Rune platelegs (t)",
    "Rune plateskirt",
    "Rune plateskirt (g)",
    "Rune plateskirt (t)",
    "Rune pouch (Emir's Arena)",
    "Rune pouch (Last Man Standing)",
    "Rune scimitar",
    "Rune scimitar (2021 Halloween event)",
    "Rune scimitar (guthix)",
    "Rune scimitar (saradomin)",
    "Rune scimitar (zamorak)",
    "Rune scimitar ornament kit (guthix)",
    "Rune scimitar ornament kit (saradomin)",
    "Rune scimitar ornament kit (zamorak)",
    "Rune shield (h1)",
    "Rune shield (h2)",
    "Rune shield (h3)",
    "Rune shield (h4)",
    "Rune shield (h5)",
    "Rune sq shield",
    "Rune sword",
    "Rune trimmed set (lg)",
    "Rune trimmed set (sk)",
    "Rune warhammer",
    "Runed sceptre",
    "Runefest shield",
    "Runite bar",
    "Runite ore",
    "Rusty sword (animation item)",
    "Sack of presents",
    "Salmon",
    "Salted chocolate mix",
    "Salted easter egg",
    "Sandwich lady bottom",
    "Sandwich lady hat",
    "Sandwich lady top",
    "Sandworms pack",
    "Sanfew serum (Last Man Standing)",
    "Santa boots",
    "Santa gloves",
    "Santa hat",
    "Santa jacket",
    "Santa mask",
    "Santa pantaloons",
    "Santa suit",
    "Santa suit (dry)",
    "Santa suit (wet)",
    "Santa's seal",
    "Sapphire",
    "Sapphire amulet",
    "Sapphire amulet (u)",
    "Sapphire key",
    "Sapphire necklace",
    "Sapphire ring",
    "Saradomin armour set (lg)",
    "Saradomin armour set (sk)",
    "Saradomin banner",
    "Saradomin brew (Last Man Standing)",
    "Saradomin full helm",
    "Saradomin kiteshield",
    "Saradomin platebody",
    "Saradomin platelegs",
    "Saradomin plateskirt",
    "Sardine",
    "Saucepan",
    "Sawdust",
    "Scaperune teleport",
    "Scythe",
    "Scythe of vitur (RuneFest 2018)",
    "Scythe sharpener",
    "Sea salt",
    "Seaweed in a box?",
    "Secret report",
    "Secret santa present",
    "Secret santa present (2021 Christmas event)",
    "Security book",
    "Seers ring (i) (Last Man Standing)",
    "Semi-precious blue gem",
    "Servant's skull",
    "Shade robe",
    "Shade robe top",
    "Shaman mask",
    "Shark (Last Man Standing)",
    "Shark (My Arm's Big Adventure)",
    "Shears",
    "Sheep's caged monkey",
    "Shiny glass",
    "Shortbow",
    "Shoulder parrot",
    "Shrimps",
    "Silk",
    "Silver bar",
    "Silver dust (2018 Birthday event)",
    "Silver ore",
    "Silver paint",
    "Silverlight",
    "Silverlight key (Captain Rovin)",
    "Silverlight key (Sir Prysin)",
    "Silverlight key (Wizard Traiborn)",
    "Simple lockbox",
    "Sine wave",
    "Situp (unobtainable item)",
    "Skeleton boots",
    "Skeleton gloves",
    "Skeleton lantern",
    "Skeleton leggings",
    "Skeleton mask",
    "Skeleton shirt",
    "Skis",
    "Skull (Mage Gower)",
    "Skull (item)",
    "Skull (unobtainable item)",
    "Skull sceptre",
    "Skull sceptre (i)",
    "Skull staples (unobtainable item)",
    "Sled (2020 Christmas event)",
    "Sleeping bag (RuneScape 2 Beta)",
    "Slice of birthday cake",
    "Sliced banana",
    "Sliding button",
    "Small chocolate egg",
    "Small fishing net",
    "Small fishing net (Evil Bob)",
    "Small snowball",
    "Smoke powder",
    "Smoked chocolate mix",
    "Smoked easter egg",
    "Snow (2021 Christmas event)",
    "Snow globe",
    "Snow imp costume body",
    "Snow imp costume feet",
    "Snow imp costume gloves",
    "Snow imp costume head",
    "Snow imp costume legs",
    "Snow imp costume tail",
    "Snow leopard toy",
    "Snow sprite (item)",
    "Snowball",
    "Snowball (animation item)",
    "Snowman ring",
    "Socks of ruin",
    "Soft clay",
    "Soft clay pack",
    "Soft clay pack (discontinued)",
    "Soul rune (Barbarian Assault)",
    "Spade",
    "Spade (RuneScape 2 Beta)",
    "Spade handle",
    "Spade head",
    "Spear (Last Man Standing)",
    "Special hot sauce",
    "Special spices",
    "Special super hot kebab",
    "Spectral potion",
    "Spell (unobtainable item)",
    "Sphinx baby",
    "Spicy chocolate mix",
    "Spicy easter egg",
    "Spider snack",
    "Spinach roll",
    "Spinning plate",
    "Spirit shield (Last Man Standing)",
    "Spookier boots",
    "Spookier gloves",
    "Spookier hood",
    "Spookier robe",
    "Spookier skirt",
    "Spooky boots",
    "Spooky gloves",
    "Spooky hood",
    "Spooky robe",
    "Spooky skirt",
    "Square sandwich",
    "Staff",
    "Staff of air",
    "Staff of earth",
    "Staff of fire",
    "Staff of the dead (Last Man Standing)",
    "Staff of water",
    "Stake",
    "Stale baguette",
    "Stale bread",
    "Star bauble",
    "Star-face",
    "Stardust",
    "Starjump (unobtainable item)",
    "Starter bow",
    "Starter staff",
    "Starter sword",
    "Statius's warhammer (Last Man Standing)",
    "Steak sandwich",
    "Steel 2h sword",
    "Steel arrow",
    "Steel arrow (Barbarian Assault)",
    "Steel axe",
    "Steel axe head",
    "Steel bar",
    "Steel battleaxe",
    "Steel chainbody",
    "Steel dagger",
    "Steel full helm",
    "Steel full helm (g)",
    "Steel full helm (t)",
    "Steel gold-trimmed set (lg)",
    "Steel gold-trimmed set (sk)",
    "Steel kiteshield",
    "Steel kiteshield (g)",
    "Steel kiteshield (t)",
    "Steel longsword",
    "Steel mace",
    "Steel med helm",
    "Steel nails",
    "Steel pick head",
    "Steel pickaxe",
    "Steel platebody",
    "Steel platebody (g)",
    "Steel platebody (t)",
    "Steel platelegs",
    "Steel platelegs (g)",
    "Steel platelegs (t)",
    "Steel plateskirt",
    "Steel plateskirt (g)",
    "Steel plateskirt (t)",
    "Steel scimitar",
    "Steel set (lg)",
    "Steel set (sk)",
    "Steel sq shield",
    "Steel sword",
    "Steel trimmed set (lg)",
    "Steel trimmed set (sk)",
    "Steel warhammer",
    "Stew",
    "Stick (2020 Christmas event)",
    "Stone (Big Cats & WWF)",
    "Stool",
    "Strange book",
    "Strange box",
    "Strange device",
    "Strange skull",
    "Strength amulet (t)",
    "Strength potion",
    "Stronghold notes",
    "Studded body",
    "Studded body (2021 Halloween event)",
    "Studded body (g)",
    "Studded body (t)",
    "Studded chaps",
    "Studded chaps (g)",
    "Studded chaps (t)",
    "Super restore (Last Man Standing)",
    "Survival token",
    "Sweet herb",
    "Swift blade",
    "Swordfish",
    "Tanning wheel",
    "Tattered book",
    "Tax relief",
    "Teal gloves",
    "Team cape i",
    "Team cape x",
    "Team cape zero",
    "Team-1 cape",
    "Team-10 cape",
    "Team-11 cape",
    "Team-12 cape",
    "Team-13 cape",
    "Team-14 cape",
    "Team-15 cape",
    "Team-16 cape",
    "Team-17 cape",
    "Team-18 cape",
    "Team-19 cape",
    "Team-2 cape",
    "Team-20 cape",
    "Team-21 cape",
    "Team-22 cape",
    "Team-23 cape",
    "Team-24 cape",
    "Team-25 cape",
    "Team-26 cape",
    "Team-27 cape",
    "Team-28 cape",
    "Team-29 cape",
    "Team-3 cape",
    "Team-30 cape",
    "Team-31 cape",
    "Team-32 cape",
    "Team-33 cape",
    "Team-34 cape",
    "Team-35 cape",
    "Team-36 cape",
    "Team-37 cape",
    "Team-38 cape",
    "Team-39 cape",
    "Team-4 cape",
    "Team-40 cape",
    "Team-41 cape",
    "Team-42 cape",
    "Team-43 cape",
    "Team-44 cape",
    "Team-45 cape",
    "Team-46 cape",
    "Team-47 cape",
    "Team-48 cape",
    "Team-49 cape",
    "Team-5 cape",
    "Team-50 cape",
    "Team-6 cape",
    "Team-7 cape",
    "Team-8 cape",
    "Team-9 cape",
    "Teleport card",
    "Tenacious indigo iris seed",
    "Tetra",
    "Thick dye",
    "Thingy",
    "Thread",
    "Throwing rope",
    "Tiara",
    "Tiara mould",
    "Tiger toy",
    "Tile",
    "Time bubble",
    "Tin ore",
    "Tinderbox",
    "Tiny fish",
    "Tomato",
    "Tomato (cookout)",
    "Tomberries",
    "Toolkit (Castle Wars)",
    "Top of sceptre",
    "Torag's helm (Last Man Standing)",
    "Torag's platelegs (Last Man Standing)",
    "Torch (animation item, Sea Slug)",
    "Torch (unobtainable item)",
    "Traiborn note",
    "Training arrows",
    "Training bow",
    "Training shield",
    "Training sword",
    "Trapped soul (2015 Halloween event)",
    "Treacle (item)",
    "Treasure clue one",
    "Treasure clue three",
    "Treasure clue two",
    "Treasure scroll",
    "Tree bauble",
    "Tree skirt",
    "Tree top",
    "Tri-jester hat",
    "Tri-jester scarf",
    "Triangle sandwich",
    "Trout",
    "Tuna",
    "Ugly halloween jumper",
    "Ultimate ironman helm",
    "Ultimate ironman platebody",
    "Ultimate ironman platelegs",
    "Unblessed symbol",
    "Uncooked apple pie",
    "Uncooked berry pie",
    "Uncooked cake",
    "Uncooked meat pie",
    "Uncooked pizza",
    "Uncooked pizza (cookout)",
    "Uncooked stew",
    "Uncut diamond",
    "Uncut emerald",
    "Uncut ruby",
    "Uncut sapphire",
    "Unfermented wine",
    "Unfermented wine (unobtainable item)",
    "Unfired bowl",
    "Unfired pie dish",
    "Unfired pot",
    "Unicorn horn (2021 Birthday event)",
    "Unicorn's caged monkey",
    "Unpainted fake magic egg",
    "Unpainted marionette",
    "Unstrung symbol",
    "Useful rock",
    "Vat (cleaned)",
    "Vat (dirty)",
    "Vault key",
    "Verac's helm (Last Man Standing)",
    "Verac's plateskirt (Last Man Standing)",
    "Vesta's longsword (Last Man Standing)",
    "Vial",
    "Vial of sorrow",
    "Vial of tears",
    "Vial of water",
    "Victor's cape (1)",
    "Victor's cape (10)",
    "Victor's cape (100)",
    "Victor's cape (1000)",
    "Victor's cape (50)",
    "Victor's cape (500)",
    "Vile ashes",
    "Voice potion",
    "Volatile mineral",
    "Volatile nightmare staff (Last Man Standing)",
    "Vyvin's wine",
    "War ship",
    "Warhammer (unobtainable item)",
    "Warrior path starter kit",
    "Washing line",
    "Waste disposal",
    "Waste gems",
    "Water rune",
    "Water rune (Barbarian Assault)",
    "Water rune pack",
    "Water talisman",
    "Water tiara",
    "Water-filled vial pack",
    "Weapon store key",
    "Wester banana",
    "Wester chocolate",
    "Wester fish",
    "Wester lemon",
    "Wester papaya",
    "Wester spices",
    "White apron",
    "White apron (Gerrant's Fishy Business)",
    "White bead",
    "White bed sheets",
    "White destabiliser",
    "White goblin mail",
    "White partyhat",
    "White toy horsey",
    "Whoopsie",
    "Wig",
    "Wilderness cape (Wilderness Wars)",
    "Wilderness cape (Wilderness Wars, Champion)",
    "Wilderness champion amulet",
    "Will and testament",
    "Willow comp bow",
    "Willow logs",
    "Willow longbow",
    "Willow shortbow",
    "Wine of zamorak",
    "Wine of zamorak (unobtainable item)",
    "Wise old man's santa hat",
    "Wise old man's teleport tablet",
    "Witch's brew",
    "Wizard hat",
    "Wizard path starter kit",
    "Wizard's mind bomb",
    "Woad leaf",
    "Wolf cloak",
    "Wolfbane lever",
    "Wooden pole",
    "Wooden shield",
    "Wooden shield (g)",
    "Wool",
    "Woolly hat",
    "Woolly scarf",
    "Wrath rune (Barbarian Assault)",
    "Yellow bead",
    "Yellow cape",
    "Yellow destabiliser",
    "Yellow dye",
    "Yellow gloves",
    "Yellow goblin mail",
    "Yellow partyhat",
    "Yellow rainbow strand",
    "Yew logs",
    "Yin yang amulet",
    "Yo-yo",
    "Zamorak armour set (lg)",
    "Zamorak armour set (sk)",
    "Zamorak banner",
    "Zamorak full helm",
    "Zamorak kiteshield",
    "Zamorak monk bottom",
    "Zamorak monk top",
    "Zamorak platebody",
    "Zamorak platelegs",
    "Zamorak plateskirt",
    "Zanaris choir",
    "Zeke's challenge scroll",
    "Zombie boots",
    "Zombie gloves",
    "Zombie head",
    "Zombie mask",
    "Zombie shirt",
    "Zombie trousers",
    "Zuriel's staff (Last Man Standing)"]

new_osrs_items = []

for x in range(0, 1885):
    osrs_items[x] = osrs_items[x].strip()
    osrs_items[x] = osrs_items[x].replace(" ", "")
    osrs_items[x] = osrs_items[x].replace("'", "")
    osrs_items[x] = osrs_items[x].replace("-", "")
    osrs_items[x] = osrs_items[x].replace("(", "")
    osrs_items[x] = osrs_items[x].replace(")", "")
    osrs_items[x] = osrs_items[x].replace("0", "")
    osrs_items[x] = osrs_items[x].replace("1", "")
    osrs_items[x] = osrs_items[x].replace("2", "")
    osrs_items[x] = osrs_items[x].replace("3", "")
    osrs_items[x] = osrs_items[x].replace("4", "")
    osrs_items[x] = osrs_items[x].replace("5", "")
    osrs_items[x] = osrs_items[x].replace("6", "")
    osrs_items[x] = osrs_items[x].replace("7", "")
    osrs_items[x] = osrs_items[x].replace("8", "")
    osrs_items[x] = osrs_items[x].replace("9", "")

new_osrs_items = [*set(osrs_items)]

new_osrs_items.sort()

print(new_osrs_items)